backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - file: "index.html"
        label: "Contenuti homepage (HTML grezzo)"
        name: "index"
        fields:
          - label: "File HTML"
            name: "body"
            widget: "code"
            default_language: "html"
