backend:
  name: git-gateway
  branch: main
  identity_url: "https://agringevo.netlify.app/.netlify/identity"
  gateway_url: "https://agringevo.netlify.app/.netlify/git"
  site_domain: "agringevo.netlify.app"

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

locale: "it"

collections:
  - name: "contenuti"
    label: "Contenuti del sito"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Titolo principale", name: "title", widget: "string" }
          - { label: "Descrizione", name: "description", widget: "text" }
